import type { Item } from "./types"

export const initialItems: Record<string, Item[]> = {
  container1: [
    {
      id: "1",
      label: "Full name",
      type: "text",
      name: "fullName",
      placeholder: "Enter your full name",
      required: true,
    },
    {
      id: "2",
      label: "Legal Age",
      type: "checkbox",
      name: "isLegalAge",
      required: true,
    },
    {
      id: "3",
      label: "Username",
      type: "text",
      name: "username",
      placeholder: "Choose a username",
      required: false,
    },
    {
      id: "4",
      label: "Birthday",
      type: "date",
      name: "birthday",
      required: false,
    },
    {
      id: "5",
      label: "Email Address",
      type: "email",
      name: "email",
      placeholder: "your.email@example.com",
      required: true,
    },
    {
      id: "6",
      label: "Phone Number",
      type: "tel",
      name: "phone",
      placeholder: "+1 (555) 123-4567",
      required: false,
    },
    {
      id: "7",
      label: "Password",
      type: "password",
      name: "password",
      required: true,
    },
    {
      id: "8",
      label: "Department",
      type: "select",
      name: "department",
      options: ["Engineering", "Marketing", "Sales", "Customer Support", "Human Resources"],
      required: false,
    },
    {
      id: "9",
      label: "Cover Letter",
      type: "textarea",
      name: "coverLetter",
      placeholder: "Tell us why you're interested in this position...",
      required: false,
    },
    {
      id: "10",
      label: "Years of Experience",
      type: "number",
      name: "experience",
      min: 0,
      max: 50,
      step: 1,
      required: false,
    },
  ],
  container2: [],
}
